### ISSUE TITLE
Internal Server Error 405 from /api/go-cam/{id} - expected 200 or 404

### ISSUE THREAD

**Issue by kimrutherford** [geneontology/go-fastapi#93] opened 2024-04-29 23:49 UTC
```sh
curl https://api.geneontology.org/api/go-cam/66187e4700001573
```
Results in:
```
Internal Server Error
```

This is a production model, but is quite new:
http://noctua.geneontology.org/workbench/noctua-visual-pathway-editor/?model_id=gomodel:66187e4700001573

**Comment by kltm** [comment] 2024-04-30 00:07
@kimrutherford Just noting that models less than two weeks (as of today, between release) old would not be expected to give results. That said, `Internal server error` would also not be the way to communicate that.

**Comment by kltm** [comment] 2024-04-30 00:08
Noting to @pgaudet that with actual use coming in on these APIs, we'll likely have some cleaning/debugging to do that will take away effort on other fronts.

**Comment by kltm** [comment] 2024-04-30 00:09
Before we start digging in too much @sierra-moxon (hello again!) @dustine32 do you have any ideas?

**Comment by sierra-moxon** [comment] 2024-05-01 00:26
notes from debugging today: the internal server error is intermittent, happens when the API loses connection to the RDF endpoint.

**Comment by sierra-moxon** [comment] 2024-06-17 19:37
retested again; no errors, I get data back from: https://api.geneontology.org/api/go-cam/66187e4700001573.

**Comment by kimrutherford** [comment] 2024-06-17 19:46
Hi @sierra-moxon

The API still returns an internal error is there is no data:
https://api.geneontology.org/api/go-cam/66187e4700001574

```
Internal Server Error
```

I expected a 404 response code.

I wasn't having a problem in the case where the model is available.

**Comment by kimrutherford** [comment] 2024-07-24 00:46
Hi.

https://api.geneontology.org/api/go-cam/66187e4700001574

We're still getting an "Internal Server Error" message if an ID isn't available, with a status code of [405 Method Not Allowed](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/405).

We'd like to be able to distinguish between missing data and server errors when looking up models.  Would we get a 405 status code if there was a server error or would one of the 500 codes be returned?

Thanks.

**Comment by kltm** [comment] 2024-07-25 22:15
It looks like we still may have to roll out a fix; I will open this issue and we'll try and get to the bottom of it as quickly as we can.

**Comment by kimrutherford** [comment] 2024-08-23 05:30
> It looks like we still may have to roll out a fix;

Hi.  Did the fix get rolled out?  I'm still getting 405 `Internal Server Error` for IDs that aren't available.

**Comment by kimrutherford** [comment] 2024-08-23 05:48
> 405 Internal Server Error

Sorry, I got that wrong.  I found the "405" with `curl --head`, but that using that curl option with the API always returns 405.  I don't feel that's a bug.

Running this command gives status code 500, with "Internal Server Error" as the body:
```
curl -v https://api.geneontology.org/api/go-cam/6690711d00002821
```

I had the same confusion in my earlier comment:
 - https://github.com/geneontology/go-fastapi/issues/93#issuecomment-2246643814

**Comment by kltm** [comment] 2024-08-24 05:01
@kimrutherford I believe that there is another fix set coming out (next week?) to the deployed API. I believe it may address this issue. (tagging @sierra-moxon)

**Comment by kltm** [comment] 2024-08-24 05:04
Just to clarify, https://api.geneontology.org/api/go-cam/6690711d00002821 (see https://model.geneontology.org/6690711d00002821) is expected to return _some_ kind of error, as it was not a public model at the time of release, but "Internal server error" is not an ideal way to express that.

**Comment by kltm** [comment] 2024-08-24 05:06
Maybe technically a dupe of https://github.com/geneontology/go-fastapi/issues/99?

**Comment by kltm** [comment] 2024-10-23 00:41
@kimrutherford Are you still seeing this error? We have had a few updates and this may be cleared.

**Comment by kimrutherford** [comment] 2024-10-23 05:13
I'm still getting 500 instead of 404 for IDs that aren't available.

For example:
```
curl -v https://api.geneontology.org/api/go-cam/66187e4700001574
```

```
...
< HTTP/2 500 
< date: Wed, 23 Oct 2024 05:11:23 GMT
< content-type: application/json
< content-length: 67
< cf-cache-status: DYNAMIC
< server: cloudflare
< cf-ray: 8d6f39dd6a951c4d-AKL
< 
* Connection #0 to host api.geneontology.org left intact
{"message":"An unexpected error occurred. Please try again later."}%  
```

**Comment by sierra-moxon** [comment] 2024-11-27 17:29
Just testing with the next release and now with this command:
```
curl -v https://api.geneontology.org/api/go-cam/66187
```
or 
```
curl -v https://api.geneontology.org/api/go-cam/66187e4700001574
```
I get: 
```
< HTTP/2 404 
< date: Wed, 27 Nov 2024 17:28:25 GMT
< content-type: application/json
< content-length: 36
< cf-cache-status: DYNAMIC
< server: cloudflare
< cf-ray: 8e93d5a72ea17646-SEA
< 
* Connection #0 to host api.geneontology.org left intact
{"detail":"GO-CAM model not found."}%       
```

Please let me know if this fits the expected behavior?

**Comment by kimrutherford** [comment] 2024-11-27 22:20
Looks good.  Thanks!

**Closed** 2024-11-27 22:23 UTC
